name: Run Tests

on:
  # On push
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout build
      uses: actions/checkout@v3
      
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: intl
    
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        
    - name: Run Tests
      run: composer qc
